var annotated_dup =
[
    [ "_card_desc", "d6/d3a/struct__card__desc.html", null ],
    [ "_sd_control_desc", "da/d28/struct__sd__control__desc.html", null ],
    [ "acoral_atomic_t", "da/daf/structacoral__atomic__t.html", null ],
    [ "acoral_block_ctr_t", "dc/d3b/structacoral__block__ctr__t.html", null ],
    [ "acoral_block_t", "da/d87/structacoral__block__t.html", null ],
    [ "acoral_comm_policy_data_t", "d5/d8c/structacoral__comm__policy__data__t.html", null ],
    [ "acoral_dev_operation", "d1/d68/structacoral__dev__operation.html", null ],
    [ "acoral_drv_ctrl", "d2/d8d/structacoral__drv__ctrl.html", null ],
    [ "acoral_evt_t", "d5/dad/structacoral__evt__t.html", null ],
    [ "acoral_intr_ctr_t", "d4/d8a/structacoral__intr__ctr__t.html", null ],
    [ "acoral_kb_info", "d6/d23/structacoral__kb__info.html", null ],
    [ "acoral_msg_t", "d8/dc2/structacoral__msg__t.html", null ],
    [ "acoral_msgctr_t", "d6/d9c/structacoral__msgctr__t.html", null ],
    [ "acoral_period_policy_data_t", "da/de2/structacoral__period__policy__data__t.html", null ],
    [ "acoral_pool_ctrl_t", "dd/d49/structacoral__pool__ctrl__t.html", null ],
    [ "acoral_pool_t", "d6/dbc/structacoral__pool__t.html", null ],
    [ "acoral_rdy_queue_t", "dc/d9f/structacoral__rdy__queue__t.html", null ],
    [ "acoral_res_api_t", "da/dea/structacoral__res__api__t.html", null ],
    [ "acoral_res_ops_t", "d2/de9/structacoral__res__ops__t.html", null ],
    [ "acoral_res_t", "d7/d12/unionacoral__res__t.html", null ],
    [ "acoral_sched_policy_t", "dc/d80/structacoral__sched__policy__t.html", null ],
    [ "acoral_screen_info", "d0/db3/structacoral__screen__info.html", null ],
    [ "acoral_spinlock_t", "db/d52/structacoral__spinlock__t.html", null ],
    [ "acoral_thread_t", "dc/d6d/structacoral__thread__t.html", null ],
    [ "acoral_ts_info", "de/d01/structacoral__ts__info.html", null ],
    [ "boot_nand_t", "d0/db6/structboot__nand__t.html", null ],
    [ "hal_ctx_t", "d4/de2/structhal__ctx__t.html", null ],
    [ "mem2_ctrl_t", "df/d2e/structmem2__ctrl__t.html", null ],
    [ "period_policy_data_t", "dc/d85/structperiod__policy__data__t.html", null ]
];